site_name: Ace of Spades 
site_url: hhttps://ace-extrenof.github.io/Ace-of-Spades
theme:
  font:
    text: Aleo 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: red 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: blue

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html

plugins:
  - glightbox
